In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
train = pd.read_csv ('Desktop/0.csv')

y=train['26.0'].astype('int')
x = train.drop('26.0',axis=1)

from sklearn.model_selection import train_test_split, cross_val_score
x_train, x_valid, y_train, y_valid = train_test_split(x,y,test_size=0.3,random_state=17)

nb_classifier = GaussianNB()
nb_classifier.fit(x_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
print('Metrics on Test Set:'
      
y_pred = nb_classifier.predict(x_valid)
      
print('Accuracy:', accuracy_score(y_valid, y_pred))
print('Precision:',precision_score(y_valid, y_pred, average='macro'))
print('Matrix:\n', confusion_matrix(y_valid, y_pred))



Metrics on Test Set:
Accuracy: 0.019473081328751432
Precision: 0.0071409873503709255
Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\aruto\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
